apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: frontend-app
        image: shouryadutt/nodejs:v1.0
      ports:
        - containerPort: 4200
